<div class="checkout-success">
    <div class="success-logo">
        <img src="<?= $this->getViewFileUrl('Boodil_Payment::images/boodil.svg'); ?>" alt="<?= __('boodil') ?>" />
    </div>
    <h1 class="page-title">
        <span class="base"><?= __("Payment Successful with Boodil"); ?></span>
    </h1>
    <p><?= __("Please go back to your original browser to see the order confirmation."); ?></p>
</div>
